services:
  frontend:
    build:
      context: ./drive-me-frontend
      dockerfile: Dockerfile
      args:
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "80:80"
    environment:
      - VITE_GOOGLE_API_KEY=${GOOGLE_API_KEY}

  backend:
    build:
      context: ./drive-me-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:99532553@db:5432/driveme?schema=public
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 99532553
      POSTGRES_DB: driveme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
